################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../Libs/rocksdb-master/util/arena.o \
../Libs/rocksdb-master/util/auto_roll_logger.o \
../Libs/rocksdb-master/util/bloom.o \
../Libs/rocksdb-master/util/build_version.o \
../Libs/rocksdb-master/util/cache.o \
../Libs/rocksdb-master/util/coding.o \
../Libs/rocksdb-master/util/comparator.o \
../Libs/rocksdb-master/util/crc32c.o \
../Libs/rocksdb-master/util/db_info_dumper.o \
../Libs/rocksdb-master/util/dynamic_bloom.o \
../Libs/rocksdb-master/util/env.o \
../Libs/rocksdb-master/util/env_hdfs.o \
../Libs/rocksdb-master/util/env_posix.o \
../Libs/rocksdb-master/util/event_logger.o \
../Libs/rocksdb-master/util/file_util.o \
../Libs/rocksdb-master/util/filter_policy.o \
../Libs/rocksdb-master/util/hash.o \
../Libs/rocksdb-master/util/hash_cuckoo_rep.o \
../Libs/rocksdb-master/util/hash_linklist_rep.o \
../Libs/rocksdb-master/util/hash_skiplist_rep.o \
../Libs/rocksdb-master/util/histogram.o \
../Libs/rocksdb-master/util/instrumented_mutex.o \
../Libs/rocksdb-master/util/iostats_context.o \
../Libs/rocksdb-master/util/ldb_cmd.o \
../Libs/rocksdb-master/util/ldb_tool.o \
../Libs/rocksdb-master/util/log_buffer.o \
../Libs/rocksdb-master/util/logging.o \
../Libs/rocksdb-master/util/memenv.o \
../Libs/rocksdb-master/util/murmurhash.o \
../Libs/rocksdb-master/util/mutable_cf_options.o \
../Libs/rocksdb-master/util/options.o \
../Libs/rocksdb-master/util/options_builder.o \
../Libs/rocksdb-master/util/options_helper.o \
../Libs/rocksdb-master/util/perf_context.o \
../Libs/rocksdb-master/util/rate_limiter.o \
../Libs/rocksdb-master/util/skiplistrep.o \
../Libs/rocksdb-master/util/slice.o \
../Libs/rocksdb-master/util/sst_dump_tool.o \
../Libs/rocksdb-master/util/statistics.o \
../Libs/rocksdb-master/util/status.o \
../Libs/rocksdb-master/util/string_util.o \
../Libs/rocksdb-master/util/sync_point.o \
../Libs/rocksdb-master/util/thread_local.o \
../Libs/rocksdb-master/util/thread_status_impl.o \
../Libs/rocksdb-master/util/thread_status_updater.o \
../Libs/rocksdb-master/util/thread_status_updater_debug.o \
../Libs/rocksdb-master/util/thread_status_util.o \
../Libs/rocksdb-master/util/thread_status_util_debug.o \
../Libs/rocksdb-master/util/vectorrep.o \
../Libs/rocksdb-master/util/xfunc.o \
../Libs/rocksdb-master/util/xxhash.o 

CC_SRCS += \
../Libs/rocksdb-master/util/arena.cc \
../Libs/rocksdb-master/util/arena_test.cc \
../Libs/rocksdb-master/util/auto_roll_logger.cc \
../Libs/rocksdb-master/util/auto_roll_logger_test.cc \
../Libs/rocksdb-master/util/autovector_test.cc \
../Libs/rocksdb-master/util/benchharness.cc \
../Libs/rocksdb-master/util/benchharness_test.cc \
../Libs/rocksdb-master/util/bloom.cc \
../Libs/rocksdb-master/util/bloom_test.cc \
../Libs/rocksdb-master/util/build_version.cc \
../Libs/rocksdb-master/util/cache.cc \
../Libs/rocksdb-master/util/cache_bench.cc \
../Libs/rocksdb-master/util/cache_test.cc \
../Libs/rocksdb-master/util/coding.cc \
../Libs/rocksdb-master/util/coding_test.cc \
../Libs/rocksdb-master/util/comparator.cc \
../Libs/rocksdb-master/util/crc32c.cc \
../Libs/rocksdb-master/util/crc32c_test.cc \
../Libs/rocksdb-master/util/db_info_dumper.cc \
../Libs/rocksdb-master/util/dynamic_bloom.cc \
../Libs/rocksdb-master/util/dynamic_bloom_test.cc \
../Libs/rocksdb-master/util/env.cc \
../Libs/rocksdb-master/util/env_hdfs.cc \
../Libs/rocksdb-master/util/env_posix.cc \
../Libs/rocksdb-master/util/env_test.cc \
../Libs/rocksdb-master/util/event_logger.cc \
../Libs/rocksdb-master/util/event_logger_test.cc \
../Libs/rocksdb-master/util/file_util.cc \
../Libs/rocksdb-master/util/filelock_test.cc \
../Libs/rocksdb-master/util/filter_policy.cc \
../Libs/rocksdb-master/util/hash.cc \
../Libs/rocksdb-master/util/hash_cuckoo_rep.cc \
../Libs/rocksdb-master/util/hash_linklist_rep.cc \
../Libs/rocksdb-master/util/hash_skiplist_rep.cc \
../Libs/rocksdb-master/util/histogram.cc \
../Libs/rocksdb-master/util/histogram_test.cc \
../Libs/rocksdb-master/util/instrumented_mutex.cc \
../Libs/rocksdb-master/util/iostats_context.cc \
../Libs/rocksdb-master/util/ldb_cmd.cc \
../Libs/rocksdb-master/util/ldb_tool.cc \
../Libs/rocksdb-master/util/log_buffer.cc \
../Libs/rocksdb-master/util/log_write_bench.cc \
../Libs/rocksdb-master/util/logging.cc \
../Libs/rocksdb-master/util/manual_compaction_test.cc \
../Libs/rocksdb-master/util/memenv.cc \
../Libs/rocksdb-master/util/memenv_test.cc \
../Libs/rocksdb-master/util/mock_env.cc \
../Libs/rocksdb-master/util/mock_env_test.cc \
../Libs/rocksdb-master/util/murmurhash.cc \
../Libs/rocksdb-master/util/mutable_cf_options.cc \
../Libs/rocksdb-master/util/options.cc \
../Libs/rocksdb-master/util/options_builder.cc \
../Libs/rocksdb-master/util/options_helper.cc \
../Libs/rocksdb-master/util/options_test.cc \
../Libs/rocksdb-master/util/perf_context.cc \
../Libs/rocksdb-master/util/rate_limiter.cc \
../Libs/rocksdb-master/util/rate_limiter_test.cc \
../Libs/rocksdb-master/util/skiplistrep.cc \
../Libs/rocksdb-master/util/slice.cc \
../Libs/rocksdb-master/util/slice_transform_test.cc \
../Libs/rocksdb-master/util/sst_dump_test.cc \
../Libs/rocksdb-master/util/sst_dump_tool.cc \
../Libs/rocksdb-master/util/statistics.cc \
../Libs/rocksdb-master/util/status.cc \
../Libs/rocksdb-master/util/string_util.cc \
../Libs/rocksdb-master/util/sync_point.cc \
../Libs/rocksdb-master/util/testharness.cc \
../Libs/rocksdb-master/util/testutil.cc \
../Libs/rocksdb-master/util/thread_list_test.cc \
../Libs/rocksdb-master/util/thread_local.cc \
../Libs/rocksdb-master/util/thread_local_test.cc \
../Libs/rocksdb-master/util/thread_status_impl.cc \
../Libs/rocksdb-master/util/thread_status_updater.cc \
../Libs/rocksdb-master/util/thread_status_updater_debug.cc \
../Libs/rocksdb-master/util/thread_status_util.cc \
../Libs/rocksdb-master/util/thread_status_util_debug.cc \
../Libs/rocksdb-master/util/vectorrep.cc \
../Libs/rocksdb-master/util/xfunc.cc \
../Libs/rocksdb-master/util/xxhash.cc 

OBJS += \
./Libs/rocksdb-master/util/arena.o \
./Libs/rocksdb-master/util/arena_test.o \
./Libs/rocksdb-master/util/auto_roll_logger.o \
./Libs/rocksdb-master/util/auto_roll_logger_test.o \
./Libs/rocksdb-master/util/autovector_test.o \
./Libs/rocksdb-master/util/benchharness.o \
./Libs/rocksdb-master/util/benchharness_test.o \
./Libs/rocksdb-master/util/bloom.o \
./Libs/rocksdb-master/util/bloom_test.o \
./Libs/rocksdb-master/util/build_version.o \
./Libs/rocksdb-master/util/cache.o \
./Libs/rocksdb-master/util/cache_bench.o \
./Libs/rocksdb-master/util/cache_test.o \
./Libs/rocksdb-master/util/coding.o \
./Libs/rocksdb-master/util/coding_test.o \
./Libs/rocksdb-master/util/comparator.o \
./Libs/rocksdb-master/util/crc32c.o \
./Libs/rocksdb-master/util/crc32c_test.o \
./Libs/rocksdb-master/util/db_info_dumper.o \
./Libs/rocksdb-master/util/dynamic_bloom.o \
./Libs/rocksdb-master/util/dynamic_bloom_test.o \
./Libs/rocksdb-master/util/env.o \
./Libs/rocksdb-master/util/env_hdfs.o \
./Libs/rocksdb-master/util/env_posix.o \
./Libs/rocksdb-master/util/env_test.o \
./Libs/rocksdb-master/util/event_logger.o \
./Libs/rocksdb-master/util/event_logger_test.o \
./Libs/rocksdb-master/util/file_util.o \
./Libs/rocksdb-master/util/filelock_test.o \
./Libs/rocksdb-master/util/filter_policy.o \
./Libs/rocksdb-master/util/hash.o \
./Libs/rocksdb-master/util/hash_cuckoo_rep.o \
./Libs/rocksdb-master/util/hash_linklist_rep.o \
./Libs/rocksdb-master/util/hash_skiplist_rep.o \
./Libs/rocksdb-master/util/histogram.o \
./Libs/rocksdb-master/util/histogram_test.o \
./Libs/rocksdb-master/util/instrumented_mutex.o \
./Libs/rocksdb-master/util/iostats_context.o \
./Libs/rocksdb-master/util/ldb_cmd.o \
./Libs/rocksdb-master/util/ldb_tool.o \
./Libs/rocksdb-master/util/log_buffer.o \
./Libs/rocksdb-master/util/log_write_bench.o \
./Libs/rocksdb-master/util/logging.o \
./Libs/rocksdb-master/util/manual_compaction_test.o \
./Libs/rocksdb-master/util/memenv.o \
./Libs/rocksdb-master/util/memenv_test.o \
./Libs/rocksdb-master/util/mock_env.o \
./Libs/rocksdb-master/util/mock_env_test.o \
./Libs/rocksdb-master/util/murmurhash.o \
./Libs/rocksdb-master/util/mutable_cf_options.o \
./Libs/rocksdb-master/util/options.o \
./Libs/rocksdb-master/util/options_builder.o \
./Libs/rocksdb-master/util/options_helper.o \
./Libs/rocksdb-master/util/options_test.o \
./Libs/rocksdb-master/util/perf_context.o \
./Libs/rocksdb-master/util/rate_limiter.o \
./Libs/rocksdb-master/util/rate_limiter_test.o \
./Libs/rocksdb-master/util/skiplistrep.o \
./Libs/rocksdb-master/util/slice.o \
./Libs/rocksdb-master/util/slice_transform_test.o \
./Libs/rocksdb-master/util/sst_dump_test.o \
./Libs/rocksdb-master/util/sst_dump_tool.o \
./Libs/rocksdb-master/util/statistics.o \
./Libs/rocksdb-master/util/status.o \
./Libs/rocksdb-master/util/string_util.o \
./Libs/rocksdb-master/util/sync_point.o \
./Libs/rocksdb-master/util/testharness.o \
./Libs/rocksdb-master/util/testutil.o \
./Libs/rocksdb-master/util/thread_list_test.o \
./Libs/rocksdb-master/util/thread_local.o \
./Libs/rocksdb-master/util/thread_local_test.o \
./Libs/rocksdb-master/util/thread_status_impl.o \
./Libs/rocksdb-master/util/thread_status_updater.o \
./Libs/rocksdb-master/util/thread_status_updater_debug.o \
./Libs/rocksdb-master/util/thread_status_util.o \
./Libs/rocksdb-master/util/thread_status_util_debug.o \
./Libs/rocksdb-master/util/vectorrep.o \
./Libs/rocksdb-master/util/xfunc.o \
./Libs/rocksdb-master/util/xxhash.o 

CC_DEPS += \
./Libs/rocksdb-master/util/arena.d \
./Libs/rocksdb-master/util/arena_test.d \
./Libs/rocksdb-master/util/auto_roll_logger.d \
./Libs/rocksdb-master/util/auto_roll_logger_test.d \
./Libs/rocksdb-master/util/autovector_test.d \
./Libs/rocksdb-master/util/benchharness.d \
./Libs/rocksdb-master/util/benchharness_test.d \
./Libs/rocksdb-master/util/bloom.d \
./Libs/rocksdb-master/util/bloom_test.d \
./Libs/rocksdb-master/util/build_version.d \
./Libs/rocksdb-master/util/cache.d \
./Libs/rocksdb-master/util/cache_bench.d \
./Libs/rocksdb-master/util/cache_test.d \
./Libs/rocksdb-master/util/coding.d \
./Libs/rocksdb-master/util/coding_test.d \
./Libs/rocksdb-master/util/comparator.d \
./Libs/rocksdb-master/util/crc32c.d \
./Libs/rocksdb-master/util/crc32c_test.d \
./Libs/rocksdb-master/util/db_info_dumper.d \
./Libs/rocksdb-master/util/dynamic_bloom.d \
./Libs/rocksdb-master/util/dynamic_bloom_test.d \
./Libs/rocksdb-master/util/env.d \
./Libs/rocksdb-master/util/env_hdfs.d \
./Libs/rocksdb-master/util/env_posix.d \
./Libs/rocksdb-master/util/env_test.d \
./Libs/rocksdb-master/util/event_logger.d \
./Libs/rocksdb-master/util/event_logger_test.d \
./Libs/rocksdb-master/util/file_util.d \
./Libs/rocksdb-master/util/filelock_test.d \
./Libs/rocksdb-master/util/filter_policy.d \
./Libs/rocksdb-master/util/hash.d \
./Libs/rocksdb-master/util/hash_cuckoo_rep.d \
./Libs/rocksdb-master/util/hash_linklist_rep.d \
./Libs/rocksdb-master/util/hash_skiplist_rep.d \
./Libs/rocksdb-master/util/histogram.d \
./Libs/rocksdb-master/util/histogram_test.d \
./Libs/rocksdb-master/util/instrumented_mutex.d \
./Libs/rocksdb-master/util/iostats_context.d \
./Libs/rocksdb-master/util/ldb_cmd.d \
./Libs/rocksdb-master/util/ldb_tool.d \
./Libs/rocksdb-master/util/log_buffer.d \
./Libs/rocksdb-master/util/log_write_bench.d \
./Libs/rocksdb-master/util/logging.d \
./Libs/rocksdb-master/util/manual_compaction_test.d \
./Libs/rocksdb-master/util/memenv.d \
./Libs/rocksdb-master/util/memenv_test.d \
./Libs/rocksdb-master/util/mock_env.d \
./Libs/rocksdb-master/util/mock_env_test.d \
./Libs/rocksdb-master/util/murmurhash.d \
./Libs/rocksdb-master/util/mutable_cf_options.d \
./Libs/rocksdb-master/util/options.d \
./Libs/rocksdb-master/util/options_builder.d \
./Libs/rocksdb-master/util/options_helper.d \
./Libs/rocksdb-master/util/options_test.d \
./Libs/rocksdb-master/util/perf_context.d \
./Libs/rocksdb-master/util/rate_limiter.d \
./Libs/rocksdb-master/util/rate_limiter_test.d \
./Libs/rocksdb-master/util/skiplistrep.d \
./Libs/rocksdb-master/util/slice.d \
./Libs/rocksdb-master/util/slice_transform_test.d \
./Libs/rocksdb-master/util/sst_dump_test.d \
./Libs/rocksdb-master/util/sst_dump_tool.d \
./Libs/rocksdb-master/util/statistics.d \
./Libs/rocksdb-master/util/status.d \
./Libs/rocksdb-master/util/string_util.d \
./Libs/rocksdb-master/util/sync_point.d \
./Libs/rocksdb-master/util/testharness.d \
./Libs/rocksdb-master/util/testutil.d \
./Libs/rocksdb-master/util/thread_list_test.d \
./Libs/rocksdb-master/util/thread_local.d \
./Libs/rocksdb-master/util/thread_local_test.d \
./Libs/rocksdb-master/util/thread_status_impl.d \
./Libs/rocksdb-master/util/thread_status_updater.d \
./Libs/rocksdb-master/util/thread_status_updater_debug.d \
./Libs/rocksdb-master/util/thread_status_util.d \
./Libs/rocksdb-master/util/thread_status_util_debug.d \
./Libs/rocksdb-master/util/vectorrep.d \
./Libs/rocksdb-master/util/xfunc.d \
./Libs/rocksdb-master/util/xxhash.d 


# Each subdirectory must supply rules for building sources it contributes
Libs/rocksdb-master/util/%.o: ../Libs/rocksdb-master/util/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


